# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sitepanda < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hokupod/sitepanda/releases/download/v0.0.5/sitepanda_0.0.5_darwin_arm64.tar.gz"
      sha256 "9080e99e0a120367aa36409898489e900aee72fae4602f07678e925addfe2bc8"

      def install
        bin.install "sitepanda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hokupod/sitepanda/releases/download/v0.0.5/sitepanda_0.0.5_linux_amd64.tar.gz"
      sha256 "b956b20e1d613dca132dfe8b739289e7a495b72ca0b4d34b3acb3927858912b6"
      def install
        bin.install "sitepanda"
      end
    end
  end
end
