# This file was generated by GoReleaser. DO NOT EDIT.
cask "fs-tracer" do
  name "fs-tracer"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fs-tracer"
  bash_completion "completions/fs-tracer.bash"
  zsh_completion "completions/_fs-tracer"
  fish_completion "completions/fs-tracer.fish"

  on_macos do
    on_intel do
      url "https://github.com/hokupod/fs-tracer/releases/download/v#{version}/fs-tracer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hokupod/fs-tracer"
      sha256 "369ff8cea9490a967649531a8aa694055a2d132a2d630da39b3ec804e59a917a"
    end
    on_arm do
      url "https://github.com/hokupod/fs-tracer/releases/download/v#{version}/fs-tracer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hokupod/fs-tracer"
      sha256 "079ce4a74c24694932c29a90b3b9d01bc5e9d92763d770b4800a546bd2779b69"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fs-tracer"]
    end
  end

  caveats do
    "This CLI is unsigned. If macOS blocks execution, remove the quarantine flag:"
    "  xattr -dr com.apple.quarantine #{HOMEBREW_PREFIX}/bin/fs-tracer"
  end

  # No zap stanza required
end
