# This file was generated by GoReleaser. DO NOT EDIT.
cask "fs-tracer" do
  name "fs-tracer"
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fs-tracer"
  bash_completion "completions/fs-tracer.bash"
  zsh_completion "completions/_fs-tracer"
  fish_completion "completions/fs-tracer.fish"

  on_macos do
    on_intel do
      url "https://github.com/hokupod/fs-tracer/releases/download/v#{version}/fs-tracer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hokupod/fs-tracer"
      sha256 "ecd7965ac1646fd36f5da9ec24bb30e3e1e25df53e8abd956a60f204a3149185"
    end
    on_arm do
      url "https://github.com/hokupod/fs-tracer/releases/download/v#{version}/fs-tracer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hokupod/fs-tracer"
      sha256 "38b782a2c5df06b4ab28426dd69d300d4c1f4db9c68b74209e12cfc33bc93b8f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fs-tracer"]
    end
  end

  caveats do
    "This CLI is unsigned. If macOS blocks execution, remove the quarantine flag:"
    "  xattr -dr com.apple.quarantine #{HOMEBREW_PREFIX}/bin/fs-tracer"
  end

  # No zap stanza required
end
