# This file was generated by GoReleaser. DO NOT EDIT.
cask "fs-tracer" do
  name "fs-tracer"
  desc ""
  homepage ""
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fs-tracer"
  bash_completion "completions/fs-tracer.bash"
  zsh_completion "completions/_fs-tracer"
  fish_completion "completions/fs-tracer.fish"

  on_macos do
    on_intel do
      url "https://github.com/hokupod/fs-tracer/releases/download/v#{version}/fs-tracer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hokupod/fs-tracer"
      sha256 "be5000e882e54464460c260f51fcfe5f6e674c18c16bbe79a915cd53ce3f0dc8"
    end
    on_arm do
      url "https://github.com/hokupod/fs-tracer/releases/download/v#{version}/fs-tracer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hokupod/fs-tracer"
      sha256 "c90131909a321fa8686e0876a3fec65c51ba4421ab837071814127e558b039eb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fs-tracer"]
    end
  end

  caveats do
    "This CLI is unsigned. If macOS blocks execution, remove the quarantine flag:"
    "  xattr -dr com.apple.quarantine #{HOMEBREW_PREFIX}/bin/fs-tracer"
  end

  # No zap stanza required
end
